Write a Python Program to Add Two Matrices?





In [3]:
import numpy as np
a=np.matrix([[1,2],[3,4]])
b=np.matrix([[1,2],[2,3]])
a+b    

matrix([[2, 4],
        [5, 7]])

Write a Python Program to Multiply Two Matrices?

In [4]:
a=np.matrix([[1,2],[3,4]])
b=np.matrix([[1,2],[2,3]])
np.matmul(a,b)

matrix([[ 5,  8],
        [11, 18]])

Write a Python Program to Transpose a Matrix?

In [5]:
a=np.matrix([[1,2],[3,4]])
a.T

matrix([[1, 3],
        [2, 4]])

Write a Python Program to Sort Words in Alphabetic Order?

In [21]:
s="Hello I study at I neuron"
s=s.lower()
l=s.split(" ")
l.sort()
l
" ".join(l)

'at hello i i neuron study'

Write a Python Program to Remove Punctuation From a String?


In [24]:
s="Hello, I study at, I neuron."
j=""
for i in s:
    if i==',' or i=='.' or i=="'":
        pass
    else:
         j=j+i
j

'Hello I study at I neuron'