Write a Python Program to find sum of array?





In [2]:
import numpy as np

In [4]:
a=np.array([1,2,3,4,5])
np.sum(a)

15

Write a Python Program to find largest element in an array? 

In [5]:
a=np.array([1,2,3,4,5])
np.max(a)

5

Write a Python Program for array rotation?

In [21]:
a=np.array([[1,2],[3,4]])
print(a)
print()
print("Transpose-->")
a.T

[[1 2]
 [3 4]]

Transpose-->


array([[1, 3],
       [2, 4]])

Write a Python Program to Split the array and add the first part to the end?

In [12]:
a=np.array([[1,2],[3,4]])
x,y=a.shape
b=a[:,:x-1]+a[:,x-1]
b

array([[3, 5],
       [5, 7]])

Write a Python Program to check if given array is Monotonic?


In [1]:
def isMonotonic(A):
   return (all(A[i] <= A[i + 1] for i in range(len(A) - 1)) or
all(A[i] >= A[i + 1] for i in range(len(A) - 1)))

A = [1,2,3,4,7,8]
print(isMonotonic(A))

True
